path: /home/ship/Documents/Cubix/libfinite/examples/controller/build/controller_test
name: Controller Tester
dev: Cubix Entertainment
output: /console/games
thumb: /home/ship/Downloads/controllerTest_Thumb.png
icon: /home/ship/Downloads/controllerTest_Icon.png
